// Modern Athletic Theme System - 2024/2025 Design

export const COLORS = {
  light: {
    // Primary - Neon Lime (Athletic Energy)
    primary: '#4ADE80',
    primaryLight: '#86EFAC',
    primaryDark: '#22C55E',
    
    // Secondary - Electric Blue
    secondary: '#38BDF8',
    secondaryLight: '#7DD3FC',
    secondaryDark: '#0EA5E9',
    
    // Accent Colors
    accent: '#A78BFA',
    accentLight: '#C4B5FD',
    gold: '#FBBF24',
    coral: '#FB7185',
    cyan: '#22D3EE',
    
    // Backgrounds - Light Athletic
    background: '#F8FAFC',
    backgroundElevated: '#FFFFFF',
    card: '#FFFFFF',
    surface: '#F1F5F9',
    surfaceElevated: '#FFFFFF',
    
    // Text
    text: '#0F172A',
    textSecondary: '#475569',
    textTertiary: '#94A3B8',
    textInverse: '#FFFFFF',
    
    // Borders
    border: '#E2E8F0',
    borderLight: '#F1F5F9',
    borderFocus: '#4ADE80',
    
    // Status
    success: '#22C55E',
    successLight: '#DCFCE7',
    warning: '#F59E0B',
    warningLight: '#FEF3C7',
    error: '#EF4444',
    errorLight: '#FEE2E2',
    info: '#3B82F6',
    infoLight: '#DBEAFE',
    
    // Sport Type Colors
    running: '#22C55E',
    triathlon: '#3B82F6',
    cycling: '#A855F7',
    swimming: '#06B6D4',
    fitness: '#F97316',
    trail: '#84CC16',
    
    // Gradients
    gradientStart: '#4ADE80',
    gradientEnd: '#22D3EE',
    gradientDark: '#0F172A',
    
    // Glass Effect
    glass: 'rgba(255, 255, 255, 0.8)',
    glassBorder: 'rgba(255, 255, 255, 0.2)',
    
    // Overlay
    overlay: 'rgba(15, 23, 42, 0.6)',
    overlayLight: 'rgba(15, 23, 42, 0.3)',
  },
  dark: {
    // Primary - Neon Lime (Athletic Energy)
    primary: '#4ADE80',
    primaryLight: '#86EFAC',
    primaryDark: '#22C55E',
    
    // Secondary - Electric Blue
    secondary: '#38BDF8',
    secondaryLight: '#7DD3FC',
    secondaryDark: '#0EA5E9',
    
    // Accent Colors
    accent: '#A78BFA',
    accentLight: '#C4B5FD',
    gold: '#FBBF24',
    coral: '#FB7185',
    cyan: '#22D3EE',
    
    // Backgrounds - Midnight Athletic
    background: '#0B0F1A',
    backgroundElevated: '#111827',
    card: '#1E293B',
    surface: '#1E293B',
    surfaceElevated: '#334155',
    
    // Text
    text: '#F8FAFC',
    textSecondary: '#CBD5E1',
    textTertiary: '#64748B',
    textInverse: '#0F172A',
    
    // Borders
    border: '#334155',
    borderLight: '#475569',
    borderFocus: '#4ADE80',
    
    // Status
    success: '#4ADE80',
    successLight: '#14532D',
    warning: '#FBBF24',
    warningLight: '#78350F',
    error: '#F87171',
    errorLight: '#7F1D1D',
    info: '#60A5FA',
    infoLight: '#1E3A5F',
    
    // Sport Type Colors
    running: '#4ADE80',
    triathlon: '#60A5FA',
    cycling: '#C084FC',
    swimming: '#22D3EE',
    fitness: '#FB923C',
    trail: '#A3E635',
    
    // Gradients
    gradientStart: '#4ADE80',
    gradientEnd: '#22D3EE',
    gradientDark: '#0B0F1A',
    
    // Glass Effect
    glass: 'rgba(30, 41, 59, 0.8)',
    glassBorder: 'rgba(255, 255, 255, 0.1)',
    
    // Overlay
    overlay: 'rgba(0, 0, 0, 0.8)',
    overlayLight: 'rgba(0, 0, 0, 0.5)',
  },
};

export const SPACING = {
  xs: 4,
  sm: 8,
  md: 12,
  lg: 16,
  xl: 20,
  xxl: 24,
  xxxl: 32,
  xxxxl: 48,
};

export const BORDER_RADIUS = {
  xs: 4,
  sm: 8,
  md: 12,
  lg: 16,
  xl: 20,
  xxl: 24,
  xxxl: 32,
  full: 9999,
};

export const SHADOWS = {
  none: {
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0,
    shadowRadius: 0,
    elevation: 0,
  },
  sm: {
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.08,
    shadowRadius: 4,
    elevation: 2,
  },
  md: {
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.12,
    shadowRadius: 8,
    elevation: 4,
  },
  lg: {
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.16,
    shadowRadius: 16,
    elevation: 8,
  },
  xl: {
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 12 },
    shadowOpacity: 0.20,
    shadowRadius: 24,
    elevation: 12,
  },
  glow: {
    shadowColor: '#4ADE80',
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0.4,
    shadowRadius: 12,
    elevation: 8,
  },
  glowBlue: {
    shadowColor: '#38BDF8',
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0.4,
    shadowRadius: 12,
    elevation: 8,
  },
};

export const TYPOGRAPHY = {
  h1: { fontSize: 32, fontWeight: '800', lineHeight: 40, letterSpacing: -0.5 },
  h2: { fontSize: 28, fontWeight: '700', lineHeight: 36, letterSpacing: -0.3 },
  h3: { fontSize: 24, fontWeight: '700', lineHeight: 32, letterSpacing: -0.2 },
  h4: { fontSize: 20, fontWeight: '600', lineHeight: 28 },
  h5: { fontSize: 18, fontWeight: '600', lineHeight: 26 },
  body1: { fontSize: 16, fontWeight: '400', lineHeight: 24 },
  body2: { fontSize: 14, fontWeight: '400', lineHeight: 20 },
  caption: { fontSize: 12, fontWeight: '500', lineHeight: 16 },
  overline: { fontSize: 11, fontWeight: '600', lineHeight: 14, letterSpacing: 1, textTransform: 'uppercase' },
  
  fontFamily: {
    regular: 'System',
    medium: 'System',
    semibold: 'System',
    bold: 'System',
  },
  
  fontSize: {
    xs: 11,
    sm: 13,
    base: 15,
    md: 16,
    lg: 18,
    xl: 20,
    xxl: 24,
    xxxl: 32,
    huge: 40,
  },
  
  fontWeight: {
    regular: '400',
    medium: '500',
    semibold: '600',
    bold: '700',
    extrabold: '800',
  },
  
  lineHeight: {
    tight: 16,
    snug: 20,
    normal: 24,
    relaxed: 28,
    loose: 32,
    spacious: 36,
    generous: 40,
  },
};

export const FONT_SIZE = TYPOGRAPHY.fontSize;

export const ANIMATION = {
  duration: {
    instant: 100,
    fast: 200,
    normal: 300,
    slow: 500,
  },
  spring: {
    gentle: { damping: 15, stiffness: 150 },
    bouncy: { damping: 10, stiffness: 200 },
    snappy: { damping: 20, stiffness: 300 },
  },
};

export const OPACITY = {
  disabled: 0.4,
  muted: 0.6,
  medium: 0.7,
  high: 0.85,
  full: 1,
};

export const GRADIENTS = {
  primary: ['#4ADE80', '#22D3EE'],
  secondary: ['#38BDF8', '#A78BFA'],
  sunset: ['#F97316', '#FB7185'],
  dark: ['#1E293B', '#0B0F1A'],
  midnight: ['#0B0F1A', '#1E293B'],
  glass: ['rgba(255,255,255,0.1)', 'rgba(255,255,255,0.05)'],
  running: ['#22C55E', '#4ADE80'],
  triathlon: ['#3B82F6', '#60A5FA'],
  cycling: ['#A855F7', '#C084FC'],
  swimming: ['#06B6D4', '#22D3EE'],
  fitness: ['#F97316', '#FB923C'],
};

export const SPORTS = [
  { id: '5k', name: '5K Run', icon: 'run' },
  { id: '10k', name: '10K Run', icon: 'run' },
  { id: 'half-marathon', name: 'Half Marathon', icon: 'run' },
  { id: 'marathon', name: 'Marathon', icon: 'run' },
  { id: 'ultra', name: 'Ultra Marathon', icon: 'run' },
  { id: 'triathlon', name: 'Triathlon', icon: 'triathlon' },
  { id: 'ironman', name: 'Ironman', icon: 'triathlon' },
  { id: 'trail', name: 'Trail Running', icon: 'mountain' },
  { id: 'spartan', name: 'Spartan Race', icon: 'fitness' },
  { id: 'hyrox', name: 'HYROX', icon: 'fitness' },
  { id: 'obstacle', name: 'Obstacle Course', icon: 'fitness' },
  { id: 'cycling', name: 'Cycling', icon: 'bike' },
  { id: 'bike-race', name: 'Bike Race', icon: 'bike' },
  { id: 'criterium', name: 'Criterium', icon: 'bike' },
  { id: 'gran-fondo', name: 'Gran Fondo', icon: 'bike' },
  { id: 'mountain-bike', name: 'Mountain Biking', icon: 'bike' },
  { id: 'duathlon', name: 'Duathlon', icon: 'run' },
  { id: 'aquathlon', name: 'Aquathlon', icon: 'swim' },
  { id: 'swimming', name: 'Open Water Swim', icon: 'swim' },
  { id: 'cross-country', name: 'Cross Country', icon: 'run' },
];

export const CONTINENTS = [
  'Africa',
  'Asia',
  'Europe',
  'North America',
  'South America',
  'Oceania',
];

export const COUNTRY_TO_CONTINENT = {
  'Algeria': 'Africa',
  'Angola': 'Africa',
  'Benin': 'Africa',
  'Botswana': 'Africa',
  'Burkina Faso': 'Africa',
  'Burundi': 'Africa',
  'Cameroon': 'Africa',
  'Cape Verde': 'Africa',
  'Central African Republic': 'Africa',
  'Chad': 'Africa',
  'Comoros': 'Africa',
  'Congo': 'Africa',
  'Democratic Republic of the Congo': 'Africa',
  'Djibouti': 'Africa',
  'Egypt': 'Africa',
  'Equatorial Guinea': 'Africa',
  'Eritrea': 'Africa',
  'Eswatini': 'Africa',
  'Ethiopia': 'Africa',
  'Gabon': 'Africa',
  'Gambia': 'Africa',
  'Ghana': 'Africa',
  'Guinea': 'Africa',
  'Guinea-Bissau': 'Africa',
  'Ivory Coast': 'Africa',
  'Kenya': 'Africa',
  'Lesotho': 'Africa',
  'Liberia': 'Africa',
  'Libya': 'Africa',
  'Madagascar': 'Africa',
  'Malawi': 'Africa',
  'Mali': 'Africa',
  'Mauritania': 'Africa',
  'Mauritius': 'Africa',
  'Morocco': 'Africa',
  'Mozambique': 'Africa',
  'Namibia': 'Africa',
  'Niger': 'Africa',
  'Nigeria': 'Africa',
  'Rwanda': 'Africa',
  'Sao Tome and Principe': 'Africa',
  'Senegal': 'Africa',
  'Seychelles': 'Africa',
  'Sierra Leone': 'Africa',
  'Somalia': 'Africa',
  'South Africa': 'Africa',
  'South Sudan': 'Africa',
  'Sudan': 'Africa',
  'Tanzania': 'Africa',
  'Togo': 'Africa',
  'Tunisia': 'Africa',
  'Uganda': 'Africa',
  'Zambia': 'Africa',
  'Zimbabwe': 'Africa',
  'Afghanistan': 'Asia',
  'Armenia': 'Asia',
  'Azerbaijan': 'Asia',
  'Bahrain': 'Asia',
  'Bangladesh': 'Asia',
  'Bhutan': 'Asia',
  'Brunei': 'Asia',
  'Cambodia': 'Asia',
  'China': 'Asia',
  'Cyprus': 'Asia',
  'Georgia': 'Asia',
  'India': 'Asia',
  'Indonesia': 'Asia',
  'Iran': 'Asia',
  'Iraq': 'Asia',
  'Israel': 'Asia',
  'Japan': 'Asia',
  'Jordan': 'Asia',
  'Kazakhstan': 'Asia',
  'Kuwait': 'Asia',
  'Kyrgyzstan': 'Asia',
  'Laos': 'Asia',
  'Lebanon': 'Asia',
  'Malaysia': 'Asia',
  'Maldives': 'Asia',
  'Mongolia': 'Asia',
  'Myanmar': 'Asia',
  'Nepal': 'Asia',
  'North Korea': 'Asia',
  'Oman': 'Asia',
  'Pakistan': 'Asia',
  'Palestine': 'Asia',
  'Philippines': 'Asia',
  'Qatar': 'Asia',
  'Saudi Arabia': 'Asia',
  'Singapore': 'Asia',
  'South Korea': 'Asia',
  'Sri Lanka': 'Asia',
  'Syria': 'Asia',
  'Taiwan': 'Asia',
  'Tajikistan': 'Asia',
  'Thailand': 'Asia',
  'Timor-Leste': 'Asia',
  'Turkey': 'Asia',
  'Turkmenistan': 'Asia',
  'United Arab Emirates': 'Asia',
  'Uzbekistan': 'Asia',
  'Vietnam': 'Asia',
  'Yemen': 'Asia',
  'Albania': 'Europe',
  'Andorra': 'Europe',
  'Armenia': 'Europe',
  'Austria': 'Europe',
  'Azerbaijan': 'Europe',
  'Belarus': 'Europe',
  'Belgium': 'Europe',
  'Bosnia and Herzegovina': 'Europe',
  'Bulgaria': 'Europe',
  'Croatia': 'Europe',
  'Cyprus': 'Europe',
  'Czech Republic': 'Europe',
  'Denmark': 'Europe',
  'Estonia': 'Europe',
  'Faroe Islands': 'Europe',
  'Finland': 'Europe',
  'France': 'Europe',
  'Georgia': 'Europe',
  'Germany': 'Europe',
  'Gibraltar': 'Europe',
  'Great Britain': 'Europe',
  'Greece': 'Europe',
  'Hungary': 'Europe',
  'Iceland': 'Europe',
  'Ireland': 'Europe',
  'Italy': 'Europe',
  'Kosovo': 'Europe',
  'Latvia': 'Europe',
  'Liechtenstein': 'Europe',
  'Lithuania': 'Europe',
  'Luxembourg': 'Europe',
  'Malta': 'Europe',
  'Moldova': 'Europe',
  'Monaco': 'Europe',
  'Montenegro': 'Europe',
  'Netherlands': 'Europe',
  'North Macedonia': 'Europe',
  'Norway': 'Europe',
  'Poland': 'Europe',
  'Portugal': 'Europe',
  'Romania': 'Europe',
  'Russia': 'Europe',
  'San Marino': 'Europe',
  'Serbia': 'Europe',
  'Slovakia': 'Europe',
  'Slovenia': 'Europe',
  'Spain': 'Europe',
  'Sweden': 'Europe',
  'Switzerland': 'Europe',
  'UK': 'Europe',
  'Ukraine': 'Europe',
  'United Kingdom': 'Europe',
  'Vatican City': 'Europe',
  'Antigua and Barbuda': 'North America',
  'Bahamas': 'North America',
  'Barbados': 'North America',
  'Belize': 'North America',
  'Canada': 'North America',
  'Costa Rica': 'North America',
  'Cuba': 'North America',
  'Dominica': 'North America',
  'Dominican Republic': 'North America',
  'El Salvador': 'North America',
  'Grenada': 'North America',
  'Guatemala': 'North America',
  'Haiti': 'North America',
  'Honduras': 'North America',
  'Jamaica': 'North America',
  'Mexico': 'North America',
  'Nicaragua': 'North America',
  'Panama': 'North America',
  'Saint Kitts and Nevis': 'North America',
  'Saint Lucia': 'North America',
  'Saint Vincent and the Grenadines': 'North America',
  'Trinidad and Tobago': 'North America',
  'United States': 'North America',
  'Argentina': 'South America',
  'Bolivia': 'South America',
  'Brazil': 'South America',
  'Chile': 'South America',
  'Colombia': 'South America',
  'Ecuador': 'South America',
  'Guyana': 'South America',
  'Paraguay': 'South America',
  'Peru': 'South America',
  'Suriname': 'South America',
  'Uruguay': 'South America',
  'Venezuela': 'South America',
  'Australia': 'Oceania',
  'Fiji': 'Oceania',
  'Kiribati': 'Oceania',
  'Marshall Islands': 'Oceania',
  'Micronesia': 'Oceania',
  'Nauru': 'Oceania',
  'New Zealand': 'Oceania',
  'Palau': 'Oceania',
  'Papua New Guinea': 'Oceania',
  'Samoa': 'Oceania',
  'Solomon Islands': 'Oceania',
  'Tonga': 'Oceania',
  'Tuvalu': 'Oceania',
  'Vanuatu': 'Oceania',
};

export const COUNTRIES = Object.keys(COUNTRY_TO_CONTINENT).sort();
